extern int lineNum;
extern int t;
extern int a;
extern int b;
extern int level;
extern int c2;
extern int sx;
extern int lc;
extern int c1;
extern int dx;
extern int inProgram;
extern int display[100];
extern char token[];
extern int sym;
extern char token[1000];
extern struct Tab tab[tmax];
extern struct ATab atab[amax];
extern struct BTab btab[bmax];
extern char stab[smax][smax];
extern double rconst[cmax];
extern struct Code code[cmax];
extern  char symbol[][100];
extern char Objs[][15];
extern char Typs[][15];
extern int errpos;
extern int p;
extern char buffer[];
extern int len;
extern int errorFlag;
